apiVersion: v1
kind: Service
metadata:
  name: mentorship
  namespace: mentorship
spec:
  selector:
    app: mentorship
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30009
  type: NodePort